Repository CS2103JAN2018-W13-B1/main, pull requests merged in 2018-04, with the labels that each got.

#119 V1.4: Collate Code
  src/main/java/seedu/address/commons/events/ui/ChangeThemeEvent.java
  src/main/java/seedu/address/commons/events/ui/OrderPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/CommandSyntaxListUtil.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/ChangeThemeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOrderCommand.java
  src/main/java/seedu/address/logic/commands/EditOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/ChangeThemeCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/EditOrderCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/DeliveryDate.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/OrderInformation.java
  src/main/java/seedu/address/model/order/Price.java
  src/main/java/seedu/address/model/order/Quantity.java
  src/main/java/seedu/address/model/order/UniqueOrderList.java
  src/main/java/seedu/address/model/order/exceptions/OrderNotFoundException.java
  src/main/java/seedu/address/model/theme/Theme.java
  src/main/java/seedu/address/storage/XmlAdaptedOrder.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/java/seedu/address/ui/OrderListPanel.java
  src/test/java/guitests/guihandles/OrderCardHandle.java
  src/test/java/guitests/guihandles/OrderListPanelHandle.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/EditOrderCommandTest.java
  src/test/java/seedu/address/model/UniqueGroupListTest.java
  src/test/java/seedu/address/model/UniqueOrderListTest.java
  src/test/java/seedu/address/model/UniquePreferenceListTest.java
  src/test/java/seedu/address/model/order/DeliveryDateTest.java
  src/test/java/seedu/address/model/order/OrderInformationTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/order/PriceTest.java
  src/test/java/seedu/address/model/order/QuantityTest.java
  src/test/java/seedu/address/model/theme/ThemeTest.java
  src/test/java/seedu/address/storage/XmlAdaptedOrderTest.java
  src/test/java/seedu/address/testutil/EditOrderDescriptorBuilder.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/OrderUtil.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/OrderCardTest.java
  src/test/java/seedu/address/ui/OrderListPanelTest.java
  src/test/java/systemtests/AddOrderCommandSystemTest.java
  src/test/java/systemtests/DeleteOrderCommandSystemTest.java
  src/test/java/systemtests/EditOrderCommandSystemTest.java
Labels: priority.high, status.reviewed

#122 V1.4: Added collated files
  .gitignore
  collated/functional/amad-person.md
  collated/test/amad-person.md
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/OrderListPanel.fxml
  src/test/data/XmlSerializableAddressBookTest/invalidOrderAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalOrdersAddressBook.xml
  src/test/java/seedu/address/storage/XmlSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: priority.high, status.reviewed

#123 V1.4: Updated application version
  src/main/java/seedu/address/MainApp.java
Labels: priority.high, status.reviewed

#124 V1.4: Updated UserGuide
  docs/UserGuide.adoc
Labels: priority.high, status.reviewed

#130 V1.4: Updated UI
  docs/images/Ui.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.high, status.reviewed

#137 Fix ListView components in Ui displaying empty cells.
  src/main/resources/view/DarkTheme.css
Labels: status.toBeReviewed, type.code

#140 Updated UserGuide [Alicia]
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/CommandSyntaxListUtil.java
Labels: priority.high, status.toBeReviewed, type.code, type.documentation

#167 Bug Fix: Updated AddOrderCommand's invalid command format message
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
Labels: priority.high, status.reviewed, type.code

#166 Bug Fix: Updated Application Name
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: priority.high, status.reviewed, type.code

#164 Bug Fix: Updated LightTheme
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
Labels: priority.high, status.reviewed, type.code

#165 Documentation Fix: UserGuide
  docs/UserGuide.adoc
Labels: priority.high, status.reviewed, type.documentation

#173 DG Update
  docs/DeveloperGuide.adoc
  docs/diagrams/AddEntrySD.pptx
  docs/diagrams/AddEventSD.pptx
  docs/diagrams/CalendarEntryClassDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UserEventClassDiagram.pptx
  docs/images/AddEntrySD.png
  docs/images/AddEventSD.png
  docs/images/CalendarEntryClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UserEventClassDiagram.png
Labels: priority.high, status.reviewed, type.documentation

#177 Fixed AddEntry Command Example
  src/main/java/seedu/address/logic/commands/AddEntryCommand.java
Labels: priority.high, severity.low, status.reviewed, type.code

#176 Fix for Default centre panel size
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/CentrePanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.high, severity.low, status.reviewed, type.code

#179 Fix Person Panel not updating information when Undo/Redo/Clear is executed.
  src/main/java/seedu/address/commons/events/ui/ResetPersonPanelEvent.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CentrePanel.java
  src/main/java/seedu/address/ui/PersonPanel.java
Labels: status.reviewed, type.code

#181 New command to edit existing calendar entries.
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/commons/util/EntryTimeConstraintsUtil.java
  src/main/java/seedu/address/commons/util/TimeUtil.java
  src/main/java/seedu/address/logic/CommandSyntaxListUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddEntryCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEntryCommand.java
  src/main/java/seedu/address/logic/commands/EditEntryCommand.java
  src/main/java/seedu/address/logic/parser/AddEntryCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditEntryCommandParser.java
  src/main/java/seedu/address/logic/parser/EditOrderCommandParser.java
  src/main/java/seedu/address/model/CalendarManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/UniqueCalendarEntryList.java
  src/main/java/seedu/address/storage/XmlAdaptedCalendarEntry.java
  src/test/java/seedu/address/commons/util/DateUtilTest.java
  src/test/java/seedu/address/commons/util/EntryTimeConstraintsUtilTest.java
  src/test/java/seedu/address/commons/util/TimeUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEntryDescriptorTest.java
  src/test/java/seedu/address/logic/commands/ListCalendarEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/ListOrderCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEntryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditEntryCommandParserTest.java
  src/test/java/seedu/address/model/UniqueCalendarEntryListTest.java
  src/test/java/seedu/address/storage/XmlCalendarManagerStorageTest.java
  src/test/java/seedu/address/testutil/CalendarEntryBuilder.java
  src/test/java/seedu/address/testutil/CalendarEntryUtil.java
  src/test/java/seedu/address/testutil/EditEntryDescriptorBuilder.java
Labels: priority.high, status.toBeReviewed, type.enhancement

#188 V1.5rc: New Application icon
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/contact_sails_icon.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.high, status.reviewed

#193 Fix Button Text Color in DarkTheme.css and made list-view cells transparent in LightTheme.css.
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
Labels: status.reviewed, type.code

#186 V1.5rc: Add Tag colours
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.high, status.toBeReviewed

#192 Bug Fix: Updated Price and Quantity Constraints
  src/main/java/seedu/address/model/order/Price.java
  src/main/java/seedu/address/model/order/Quantity.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.high, status.reviewed, type.code

#194 Project Portfolio Page [Jing Zhe]
  ]
  docs/AboutUs.adoc
  docs/team/jingzhe.adoc
Labels: priority.high, status.toBeReviewed, type.documentation

#184 Project Portfolio Page [Alicia]
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/team/aliciaho.adoc
Labels: priority.high, status.reviewed, type.documentation

#196 V1.5rc: Update Orders
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/ChangeOrderStatusCommand.java
  src/main/java/seedu/address/logic/commands/EditOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedOrder.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/java/seedu/address/ui/OrderListPanel.java
  src/main/resources/view/OrderStatusDone.css
  src/main/resources/view/OrderStatusOngoing.css
  src/test/data/XmlSerializableAddressBookTest/invalidOrderAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalOrdersAddressBook.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/storage/XmlAdaptedOrderTest.java
  src/test/java/seedu/address/testutil/EditOrderDescriptorBuilder.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: priority.high, status.reviewed, type.code

#197 Project Portfolio Page [Aadyaa]
  collated/functional/AJZ1995.md
  collated/functional/SuxianAlicia-reused.md
  collated/functional/SuxianAlicia.md
  collated/functional/amad-person.md
  collated/test/AJZ1995.md
  collated/test/SuxianAlicia.md
  collated/test/amad-person.md
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/team/aadyaamaddi.adoc
Labels: priority.high, status.reviewed, type.documentation

#195 Minor language updates in Developer Guide
  docs/DeveloperGuide.adoc
Labels: status.reviewed, type.documentation

#201 Added Glossary to UserGuide
  docs/UserGuide.adoc
Labels: priority.high, status.reviewed, type.documentation

#208 Bug fix: Selecting selected person while calendar is displayed will not display Person Panel.
  collated/functional/AJZ1995.md
  collated/functional/SuxianAlicia.md
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/DisplayPersonPanelRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/ResetPersonPanelRequestEvent.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/ui/CenterPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/PersonPanel.java
  src/main/resources/view/CenterPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/CalendarPanelHandle.java
  src/test/java/guitests/guihandles/PersonPanelHandle.java
  src/test/java/seedu/address/ui/PersonPanelTest.java
Labels: priority.high, status.reviewed, type.code

#209 Bug Fix: Lack of Tag Colour and Update of Person Card to Person Panel
  src/main/java/seedu/address/ui/PersonPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
Labels: status.reviewed, type.bug

#210 Calendar Jump Update
  collated/functional/SuxianAlicia.md
  collated/test/SuxianAlicia.md
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/CalendarEntryPanelSelectionChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/ChangeCalendarDateRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/ChangeCalendarViewRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/DisplayCalendarRequestEvent.java
  src/main/java/seedu/address/logic/CommandSyntaxListUtil.java
  src/main/java/seedu/address/logic/commands/AddEntryCommand.java
  src/main/java/seedu/address/logic/commands/CalendarJumpCommand.java
  src/main/java/seedu/address/logic/commands/EditEntryCommand.java
  src/main/java/seedu/address/logic/commands/ViewCalendarCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CalendarJumpCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/CalendarEntry.java
  src/main/java/seedu/address/model/event/EndTime.java
  src/main/java/seedu/address/model/event/StartTime.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/CenterPanel.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/CalendarJumpCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCalendarCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CalendarJumpCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalLocalDates.java
Labels: priority.high, status.reviewed, type.enhancement

#212 UserGuide Update
  docs/UserGuide.adoc
  docs/images/ContactSails_Interface_Breakdown.png
  docs/images/ContactSails_Light_Theme.png
  docs/images/OrderAdd.png
  docs/images/OrderDeleteInit.png
  docs/images/OrderDeleteResult.png
  docs/images/OrderEditInit.png
  docs/images/OrderEditResult.png
  docs/images/OrderStatusResult.png
  docs/images/OrdersInitialAddressbook.png
Labels: priority.high, status.toBeReviewed, type.documentation

#213 UserGuide Update: Calendar and Calendar Entries Section
  docs/UserGuide.adoc
  docs/images/Calendar_DoubleClick_Error.png
  docs/images/Calendar_Entry_Card.png
  docs/images/Calendar_Month_View.png
  docs/images/Edit_Entry_After.png
  docs/images/Edit_Entry_Before.png
Labels: priority.high, status.toBeReviewed, type.documentation

#223 README Update
  README.adoc
  ]
  docs/images/Ui.png
Labels: status.reviewed, type.admin

#222 Calendar Panel Update
  collated/functional/SuxianAlicia.md
  src/main/java/seedu/address/commons/util/CalendarEntryConversionUtil.java
  src/main/java/seedu/address/commons/util/TimeUtil.java
  src/main/java/seedu/address/logic/commands/ViewBackCommand.java
  src/main/java/seedu/address/logic/commands/ViewCalendarCommand.java
  src/main/java/seedu/address/logic/commands/ViewNextCommand.java
  src/main/java/seedu/address/logic/commands/ViewTodayCommand.java
  src/main/java/seedu/address/model/CalendarManager.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/CenterPanel.java
  src/main/java/seedu/address/ui/util/CalendarFxUtil.java
  src/main/resources/view/CalendarPanel.fxml
  src/test/java/guitests/guihandles/CalendarPanelHandle.java
  src/test/java/guitests/guihandles/CenterPanelHandle.java
  src/test/java/seedu/address/logic/commands/ViewBackCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCalendarCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewNextCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewTodayCommandTest.java
  src/test/java/seedu/address/testutil/TypicalBaseEvents.java
  src/test/java/seedu/address/ui/CalendarPanelTest.java
Labels: status.reviewed, type.code, type.tests

#221 Orders: Tests
  src/main/java/seedu/address/logic/commands/EditOrderCommand.java
  src/main/java/seedu/address/logic/parser/ChangeOrderStatusCommandParser.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/ChangeOrderStatusCommandTest.java
  src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
  src/test/java/seedu/address/logic/commands/EditOrderCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ChangeOrderStatusCommandParserTest.java
  src/test/java/seedu/address/model/order/DeliveryDateTest.java
  src/test/java/seedu/address/model/order/OrderInformationTest.java
  src/test/java/seedu/address/model/order/OrderStatusTest.java
  src/test/java/seedu/address/model/order/PriceTest.java
  src/test/java/seedu/address/model/order/QuantityTest.java
  src/test/java/systemtests/EditOrderCommandSystemTest.java
Labels: status.reviewed, type.tests

#224 Calendar Entry List Clear Update
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/CommandSyntaxListUtil.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EntryListClearCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/EntryListClearCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: status.reviewed, type.enhancement

#214 Updated Developer Guide : Person Panel Section
  docs/DeveloperGuide.adoc
  docs/diagrams/SelectionPersonPanelSequenceDiagram.pptx
  docs/images/PersonPanelLayout.PNG
  docs/images/SelectionPersonPanelSequenceDiagram.PNG
Labels: priority.high, status.toBeReviewed, type.documentation

#217 Standardise UserGuide
  docs/UserGuide.adoc
  docs/images/AddNewPerson.png
  docs/images/EditPersonAfter.png
  docs/images/EditPersonBefore.png
  docs/images/GroupDeleteRefresh.png
  docs/images/GroupDeleteWarning.png
  docs/images/OrderDeleteInit.png
  docs/images/OrderDeleteResult.png
  docs/images/Start.PNG
  docs/images/add.png
  docs/images/edit.png
Labels: priority.high, status.reviewed, type.documentation

#226 Update DevGuide and Project Portfolio
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ChangingThemesDiagrams.pptx
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/OrderManagementUMLDiagrams.pptx
  docs/diagrams/UiComponentClassDiagramUpdated.pptx
  docs/images/AddOrderSeqDiagram.png
  docs/images/ChangeOrderStatusSeqDiagram.png
  docs/images/DeleteOrderSeqDiagram.png
  docs/images/EditOrderSeqDiagram.png
  docs/images/ForkAndClone.png
  docs/images/HighLevelSequenceDiagramChangeTheme.png
  docs/images/HighLevelSequenceDiagramForOrderAdd.png
  docs/images/ImportWindowFirstScreen.png
  docs/images/IntelliJWelcomeScreen.png
  docs/images/OrderUMLDiagram.png
  docs/images/PersonPanelLayout.png
  docs/images/PreferenceWarning1.png
  docs/images/PreferenceWarning2.png
  docs/images/SelectContactProcess.png
  docs/images/SelectionPersonPanelSequenceDiagram.png
  docs/images/ThemeClassUMLDiagram.png
  docs/images/UMLDiagramOrderCommandsLogic.png
  docs/images/UiClassDiagram.png
  docs/images/UniqueOrderListUMLDiagram.png
  docs/images/Warning3.png
  docs/team/aadyaamaddi.adoc
Labels: priority.high, status.reviewed, type.documentation

#227 Final CleanUp
  collated/functional/AJZ1995.md
  collated/functional/SuxianAlicia-reused.md
  collated/functional/SuxianAlicia.md
  collated/functional/amad-person.md
  collated/test/AJZ1995.md
  collated/test/SuxianAlicia-reused.md
  collated/test/SuxianAlicia.md
  collated/test/amad-person.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ChangingThemesDiagrams.pptx
  docs/images/HighLevelSequenceDiagramChangeTheme.png
  docs/team/aadyaamaddi.adoc
  src/main/java/seedu/address/commons/events/model/ChangeOrderStatusEvent.java
  src/main/java/seedu/address/commons/events/ui/ChangeThemeEvent.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/ChangeOrderStatusCommand.java
  src/main/java/seedu/address/logic/commands/EditOrderCommand.java
  src/main/java/seedu/address/logic/parser/ChangeOrderStatusCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/DeliveryDate.java
  src/main/java/seedu/address/model/order/OrderInformation.java
  src/main/java/seedu/address/model/order/OrderStatus.java
  src/main/java/seedu/address/model/order/Price.java
  src/main/java/seedu/address/model/order/Quantity.java
  src/main/java/seedu/address/model/order/UniqueOrderList.java
  src/main/java/seedu/address/model/order/exceptions/DuplicateOrderException.java
  src/main/java/seedu/address/model/theme/Theme.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedOrder.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/java/seedu/address/ui/PersonPanel.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/ChangeOrderStatusCommandTest.java
  src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteOrderCommandTest.java
  src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ChangeOrderStatusCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ChangeThemeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteOrderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditOrderCommandParserTest.java
  src/test/java/seedu/address/model/UniqueOrderListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedOrderTest.java
  src/test/java/seedu/address/testutil/OrderUtil.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/systemtests/AddOrderCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteOrderCommandSystemTest.java
  src/test/java/systemtests/EditOrderCommandSystemTest.java
Labels: priority.high, status.toBeReviewed, type.admin, type.code, type.tests

#231 Address book SystemTest Update
  collated/test/SuxianAlicia.md
  src/main/java/seedu/address/logic/commands/EditEntryCommand.java
  src/main/java/seedu/address/logic/commands/EditOrderCommand.java
  src/main/java/seedu/address/logic/commands/ListCalendarEntryCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entry/EntryTitle.java
  src/main/java/seedu/address/model/entry/UniqueCalendarEntryList.java
  src/main/java/seedu/address/model/order/UniqueOrderList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/RightPanel.java
  src/main/resources/view/RightPanel.fxml
  src/test/java/guitests/AddressBookGuiTest.java
  src/test/java/guitests/HelpWindowTest.java
  src/test/java/guitests/guihandles/CenterPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/RightPanelHandle.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/commons/util/EntryTimeConstraintsUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEntryDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditOrderCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEntryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditEntryCommandParserTest.java
  src/test/java/seedu/address/model/UniqueCalendarEntryListTest.java
  src/test/java/seedu/address/model/UniqueOrderListTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalCalendarEntries.java
  src/test/java/seedu/address/ui/CalendarPanelTest.java
  src/test/java/seedu/address/ui/RightPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddEntryCommandSystemTest.java
  src/test/java/systemtests/AddOrderCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteEntryCommandSystemTest.java
  src/test/java/systemtests/DeleteOrderCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/EditEntryCommandSystemTest.java
  src/test/java/systemtests/EditOrderCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
Labels: priority.high, status.reviewed, type.code, type.tests

#230 Export: Tests and Documentation
  collated/functional/A0143487X.md
  collated/test/A0143487X.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/kevinyeong.adoc
  src/main/java/seedu/address/commons/exceptions/FileExistsException.java
  src/main/java/seedu/address/commons/exceptions/IllegalFilenameException.java
  src/main/java/seedu/address/logic/commands/ExportListedOrdersCommand.java
  src/main/java/seedu/address/logic/commands/ExportListedPersonsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportListedOrdersCommandParser.java
  src/main/java/seedu/address/logic/parser/ExportListedPersonsCommandParser.java
  src/main/java/seedu/address/logic/parser/ExportToCsvCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ExportListedOrdersCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ExportListedPersonsCommandParserTest.java
Labels: priority.high, status.reviewed, type.documentation, type.enhancement

#233 UG Fix
  collated/functional/A0143487X.md
  collated/functional/SuxianAlicia.md
  collated/functional/amad-person.md
  collated/test/A0143487X.md
  collated/test/AJZ1995.md
  collated/test/SuxianAlicia-reused.md
  collated/test/SuxianAlicia.md
  collated/test/amad-person.md
  docs/UserGuide.adoc
  docs/images/BeforeGroupDelete.png
  docs/images/ManagingPersonsInit.png
  docs/images/OrderDeleteInit.png
  docs/images/OrderDeleteResult.png
  src/test/java/seedu/address/logic/commands/EditOrderCommandTest.java
Labels: priority.high, status.toBeReviewed, type.documentation

#235 Sample Data [CalendarEntry] Update
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.high, status.toBeReviewed, type.code

#236 Fixed description at 5.7.1 of UG.
  docs/UserGuide.adoc
Labels: priority.high, status.reviewed, type.documentation

#237 Sample Data for Orders
  docs/images/Ui.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.high, type.admin, type.code

#238 DG Final Update
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UiComponentClassDiagram.PNG
  docs/UiComponentClassDiagram.pptx
  docs/diagrams/AddEntrySD.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagramUpdated.pptx
  docs/images/AddEntrySD.png
  docs/images/CalendarPanelSD.png
  docs/images/UiClassDiagram.png
  docs/team/suxianalicia.adoc
  src/main/java/seedu/address/commons/util/EntryTimeConstraintsUtil.java
  src/main/java/seedu/address/ui/CalendarPanel.java
Labels: priority.high, status.reviewed, type.documentation
