Repository CS2103JAN2018-W13-B1/main, pull requests merged in 2018-03, with the labels that each got.

#38 Week 7 Enhancement Model Component
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/model/tag/exceptions/TagNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalTags.java
Labels: status.reviewed, type.enhancement

#37 Week 7 Enhancement: Logic Component
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: status.reviewed, type.enhancement

#42 Week 7: Updated README
  README.adoc
  docs/DeveloperGuide.adoc
Labels: status.toBeReviewed, type.task

#43 Week 7: User Stories, Glossary
  docs/DeveloperGuide.adoc
Labels: status.toBeReviewed, type.task

#40 Week 7: Use Cases
  docs/DeveloperGuide.adoc
Labels: status.toBeReviewed, type.task

#41 Week 7: Target User Profile, Value Proposition, NFR
  docs/DeveloperGuide.adoc
Labels: status.reviewed, type.task

#45 Updated name of application in documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: status.toBeReviewed, type.task

#39 Week 7 Enhancement UI Component
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: status.toBeReviewed

#54 Updated About Us [Aadyaa]
  docs/AboutUs.adoc
  docs/images/aadyaa.jpg
  docs/images/damithc.jpg
Labels: status.toBeReviewed, type.documentation

#58 Updated UserGuide
  docs/UserGuide.adoc
Labels: status.reviewed, type.documentation

#55 Updated README [Work In Progress]
  README.adoc
Labels: status.toBeReviewed, type.documentation

#57 Updated DeveloperGuide
  docs/DeveloperGuide.adoc
Labels: status.toBeReviewed, type.documentation

#63 Updated AboutUs.adoc
  docs/AboutUs.adoc
  docs/images/suxianalicia.JPG
  docs/images/yijinl.jpg
Labels: status.reviewed, type.documentation

#64 Updated Ui of ContactSails
  docs/images/Ui.png
Labels: status.reviewed, type.documentation

#53 V1.1: Find by tag enhancement
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/model/person/TagsContainKeywordsPredicate.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
  src/test/java/seedu/address/model/person/TagsContainKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: status.reviewed, type.enhancement

#51 Added autocomplete functionality for commands
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/CommandSyntaxListUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: status.toBeReviewed, type.enhancement

#65 Added autocomplete for the new FindTag command
  src/main/java/seedu/address/logic/CommandSyntaxListUtil.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
Labels: status.toBeReviewed, type.enhancement

#67 Added Kevin Yeong photo, Proj portfolio and section in AboutUs
  docs/AboutUs.adoc
  docs/images/kevinyeong.jpg
  docs/team/kevinyeong.adoc
Labels: status.toBeReviewed, type.documentation

#69 Changed picture and updated UserGuide
  docs/UserGuide.adoc
  docs/images/aadyaa.jpg
Labels: status.toBeReviewed, type.documentation

#74 Added Feature Contributions in DevGuide Appendix B
  docs/DeveloperGuide.adoc
Labels: priority.high, status.toBeReviewed, type.documentation

#52 Orders: Implemented ability to add orders to ContactSails
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/order/DeliveryDate.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/OrderInformation.java
  src/main/java/seedu/address/model/order/Price.java
  src/main/java/seedu/address/model/order/Quantity.java
  src/main/java/seedu/address/model/order/UniqueOrderList.java
  src/main/java/seedu/address/model/order/exceptions/OrderNotFoundException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/UniqueGroupListTest.java
  src/test/java/seedu/address/model/UniqueOrderListTest.java
  src/test/java/seedu/address/model/UniquePreferenceListTest.java
  src/test/java/seedu/address/model/order/DeliveryDateTest.java
  src/test/java/seedu/address/model/order/OrderInformationTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/order/PriceTest.java
  src/test/java/seedu/address/model/order/QuantityTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/OrderUtil.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddOrderCommandSystemTest.java
Labels: status.toBeReviewed, type.epic

#76 Developer Guide Feature Contribution [Alicia]
  docs/DeveloperGuide.adoc
Labels: priority.high, status.toBeReviewed, type.documentation

#83 V1.2: Updated User Guide for OrderCommands
  docs/UserGuide.adoc
Labels: priority.high, status.toBeReviewed, type.documentation

#88 V1.2: Update Developer Guide [ready for review]
  docs/DeveloperGuide.adoc
  docs/images/OrderListCardFXMLRender.png
  docs/images/OrderUMLDiagram.png
  docs/images/PersonOrderAssociationUMLDiagram.png
Labels: priority.high, status.toBeReviewed, type.documentation

#87 V1.2 Documentation Update [Alicia]
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddEventSD.pptx
  docs/diagrams/CalendarClassDiagram.pptx
  docs/images/AddEventSD.png
  docs/images/CalendarClassDiagram.png
Labels: priority.high, status.toBeReviewed, type.documentation

#89 V1.2 Delete groups and preference Commands
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/model/AddressBookChangedEvent.java
  src/main/java/seedu/address/logic/CommandSyntaxListUtil.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePreferenceCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePreferenceCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePreferenceCommandParserTest.java
Labels: status.toBeReviewed, type.enhancement

#91 V1.2: Updated UI Mockup with actual screenshot
  docs/images/Ui.png
Labels: priority.high, status.toBeReviewed

#81 V1.2: Delete orders, Storage and UI
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/OrderPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/CommandSyntaxListUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteOrderCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/XmlAdaptedOrder.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/java/seedu/address/ui/OrderListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/OrderListPanel.fxml
  src/test/data/XmlSerializableAddressBookTest/invalidOrderAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalOrdersAddressBook.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteOrderCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteOrderCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedOrderTest.java
  src/test/java/seedu/address/storage/XmlSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddOrderCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteOrderCommandSystemTest.java
Labels: priority.high, status.toBeReviewed, type.task

#101 Update Developer Guide
  docs/DeveloperGuide.adoc
Labels: priority.high, status.reviewed, type.documentation

#103 Changed Command Word for group and preference related commands
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/logic/commands/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/FindPreferenceCommand.java
Labels: status.toBeReviewed, type.code

#104 Edited Implementation (4.1) in DevGuide
  docs/DeveloperGuide.adoc
Labels: priority.high, status.toBeReviewed, type.documentation

#105 Updated Design section in DevGuide
  docs/DeveloperGuide.adoc
Labels: priority.high, status.reviewed, type.documentation

#98 V1.3: Change themes
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/events/ui/ChangeThemeEvent.java
  src/main/java/seedu/address/logic/CommandSyntaxListUtil.java
  src/main/java/seedu/address/logic/commands/ChangeThemeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ChangeThemeCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/theme/Theme.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LightTheme.css
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ChangeThemeCommandParserTest.java
  src/test/java/seedu/address/model/theme/ThemeTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.medium, status.toBeReviewed

#106 System Tests for Delete Group and Delete Preference.
  src/test/java/seedu/address/testutil/TypicalGroups.java
  src/test/java/systemtests/DeleteGroupCommandSystemTest.java
  src/test/java/systemtests/DeleteOrderCommandSystemTest.java
  src/test/java/systemtests/DeletePreferenceCommandSystemTest.java
  src/test/java/systemtests/FindGroupCommandSystemTest.java
  src/test/java/systemtests/FindPreferenceCommandSystemTest.java
Labels: status.reviewed, type.tests

#99 V1.3: Edit Orders
  src/main/java/seedu/address/commons/events/model/AddressBookChangedEvent.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditOrderCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/UniqueOrderList.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/test/java/guitests/guihandles/OrderCardHandle.java
  src/test/java/guitests/guihandles/OrderListPanelHandle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditOrderCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditOrderCommandParserTest.java
  src/test/java/seedu/address/testutil/EditOrderDescriptorBuilder.java
  src/test/java/seedu/address/ui/OrderCardTest.java
  src/test/java/seedu/address/ui/OrderListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/EditOrderCommandSystemTest.java
Labels: priority.high, status.reviewed

#110 V1.3: Updated ContactSails version
  src/main/java/seedu/address/MainApp.java
Labels: priority.high
